---
- name: Converge
  hosts: all
  become: true
  gather_facts: false

  roles:
    - robertdebock.bootstrap
    - robertdebock.buildtools
    - robertdebock.cargo
    - robertdebock.git
    - ansible-role-sudo-pair
