---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="amazonlinux" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="unstable"
    - image="fedora" tag="30"
    - image="fedora" tag="latest"
    - image="fedora" tag="rawhide"
    - image="ubuntu" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "NHfqmbLYdL5xPryhKjH2ptk1e6joJp4S98VOUzkec+N3ReBRYSVCknHXwLyGy+2fgJLkXIwjq6Y2iKMMmTXaJG1uXsWSF77hP5EKWSVeQB5BoFhrfVo97c1JB1IgqhXz8pjM4EbdHo04KIs8erYVo9QiUTSzdw+GtDsQtroVp/wgM5Ty/ZFjHwWqcjuGWUr6dpItvUXKyGP47PMlEJC1f+DitTWSr0grgbPV7ZIsrO3mf48DIHyQe9C+vtVhMGTj9QGHxjqTrniyIhQHgkml1y/DGY5HFgx4bqDud042LJJqpGvUsHU8r8Yyza+ZtkRl4DHUZt3JS72+lagOJQvE5G+OtzU/Xn1zO859yy1uGAqTA4J7z4qNbtHfJ2lKf4cPy0zzw2KTxrO4YSJjvwBaNEtbkNp0WnTFyUwThmQGpdA7EuN6UZfFjWvMoLWAm2OfBYbKm3IejCjA1z6sV1QEWvcsGHbUatdm1yPQe9uEYA6aR7T3t+UfHWHP8f3M64jUv6EpZwjwavtauVZKw1SVtZuboRUCPlIqlMug9kJzfj5DH6W53hS0bGhKNGnZHmINg9eQcQa0dv6gavKGN1TgnIPlqYeTA/yM6fPnfoJn1XVK/svSKkxtQfpAd7QgkXc1SR9uF21UzVJkt3SZBHI3PGkG9vwohP0uNJalLuVHfYk="
  email: false
