---
sudo: required
language: python
services: docker

env:
  - version=">=2.4,<2.5" distro="alpine-latest" expectation="fail"
  - version=">=2.5,<2.6" distro="alpine-latest" expectation="fail"
  - version=">=2.6,<2.7" distro="alpine-latest" expectation="fail"
  - version=">=2.4,<2.5" distro="alpine-edge" expectation="fail"
  - version=">=2.5,<2.6" distro="alpine-edge" expectation="fail"
  - version=">=2.6,<2.7" distro="alpine-edge" expectation="fail"
  - version=">=2.4,<2.5" distro="archlinux"
  - version=">=2.5,<2.6" distro="archlinux"
  - version=">=2.6,<2.7" distro="archlinux"
  - version=">=2.4,<2.5" distro="centos-6" expectation="fail"
  - version=">=2.5,<2.6" distro="centos-6" expectation="fail"
  - version=">=2.6,<2.7" distro="centos-6" expectation="fail"
  - version=">=2.4,<2.5" distro="centos-latest"
  - version=">=2.5,<2.6" distro="centos-latest"
  - version=">=2.6,<2.7" distro="centos-latest"
  - version=">=2.4,<2.5" distro="debian-latest"
  - version=">=2.5,<2.6" distro="debian-latest"
  - version=">=2.6,<2.7" distro="debian-latest"
  - version=">=2.4,<2.5" distro="debian-stable"
  - version=">=2.5,<2.6" distro="debian-stable"
  - version=">=2.6,<2.7" distro="debian-stable"
  - version=">=2.4,<2.5" distro="debian-unstable"
  - version=">=2.5,<2.6" distro="debian-unstable"
  - version=">=2.6,<2.7" distro="debian-unstable"
  - version=">=2.4,<2.5" distro="fedora-latest"
  - version=">=2.5,<2.6" distro="fedora-latest"
  - version=">=2.6,<2.7" distro="fedora-latest"
  - version=">=2.4,<2.5" distro="fedora-rawhide"
  - version=">=2.5,<2.6" distro="fedora-rawhide"
  - version=">=2.6,<2.7" distro="fedora-rawhide"
  - version=">=2.4,<2.5" distro="opensuse-leap"
  - version=">=2.5,<2.6" distro="opensuse-leap"
  - version=">=2.6,<2.7" distro="opensuse-leap"
  - version=">=2.4,<2.5" distro="opensuse-tumbleweed"
  - version=">=2.5,<2.6" distro="opensuse-tumbleweed"
  - version=">=2.6,<2.7" distro="opensuse-tumbleweed"
  - version=">=2.4,<2.5" distro="ubuntu-artful"
  - version=">=2.5,<2.6" distro="ubuntu-artful"
  - version=">=2.6,<2.7" distro="ubuntu-artful"
  - version=">=2.4,<2.5" distro="ubuntu-latest"
  - version=">=2.5,<2.6" distro="ubuntu-latest"
  - version=">=2.6,<2.7" distro="ubuntu-latest"
  - version=">=2.4,<2.5" distro="ubuntu-devel"
  - version=">=2.5,<2.6" distro="ubuntu-devel"
  - version=">=2.6,<2.7" distro="ubuntu-devel"

matrix:
  allow_failures:
    - env: version=">=2.4,<2.5" distro="alpine-edge"
    - env: version=">=2.5,<2.6" distro="alpine-edge"
    - env: version=">=2.6,<2.7" distro="alpine-edge"
    - env: version=">=2.4,<2.5" distro="debian-unstable"
    - env: version=">=2.5,<2.6" distro="debian-unstable"
    - env: version=">=2.6,<2.7" distro="debian-unstable"
    - env: version=">=2.4,<2.5" distro="fedora-rawhide"
    - env: version=">=2.5,<2.6" distro="fedora-rawhide"
    - env: version=">=2.6,<2.7" distro="fedora-rawhide"
    - env: version=">=2.4,<2.5" distro="ubuntu-devel"
    - env: version=">=2.5,<2.6" distro="ubuntu-devel"
    - env: version=">=2.6,<2.7" distro="ubuntu-devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install ansible"${version}"
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "a6zfNevsfe8C140j2yC2OkLUYmLeUYDLE5sC6O3Pl7pwi6zX4f2/4eKGQaT/Cr8gEoK5BIBgiZ7NBS3152chJSnmxQYmyVol4JXxBrE9nRyzQk24za0l3035Kvodj15KccsPeHIZ/W7qyjxz5aZK/qNnG8pqgyuyCBnxcJ4KYgK5bPRdDf+kXUmSEckeJO89NJzZPgi2o2Qd3boQ7JpBRJpL3OFbr51fVzdz5IaFEeWDwYeqyUXDcCczjy8o3iQVkt6VbGbo6wM/Ut2hNGpBFBfDvS6IBbP/p6i8PsG3yAbjwflAuzkMP98SzZLWzPOEN3ZOZGKu50HmLDshXHDPi9SjZ0Uv2XoYNb8Ae9GmW9a4w5Cu17XYNMxJmgEPVxIlg2DxCZlXgFssxLeDaJGM7IyQ991n8mh1gbpvKlmBMNeSsss94fhf4NnthinXMZcX3ASiUADvzCTUE0b7klJGYTzf/eLvo+Y7phbcqnal+Lf3D10sna/0rGKFA8X6omBdfhtlrIRIadTUxLEPX6nvk1Rf7V1qVy1mmdOi0L0cyma3VMhKU5p8eTftdI4ZeqXBu7L/0HncLERToT7jjqld2lfuB85KcfgqWwLrGN3xJL6fgtS4jvAOhqjqt+K7ckJHuK4b0vvdy9ZqtuzhhP7kRzbrz4ylXc+tbzN3hUX6AI8="
  email: false
