---
# tasks file for sudo-pair
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: install requirements
  package:
    name: "{{ item }}"
  with_items:
    - "{{ sudo_pair_requirements }}"
  environment:
    ANSIBLE_SQUASH_ACTIONS: unset

- name: download and unpack software
  unarchive:
    src: "{{ sudo_pair_url }}"
    dest: /tmp
    remote_src: yes

- name: build software
  command: cargo build --release
  args:
    chdir: "{{ sudo_pair_unpack_directory }}"
    creates: "{{ sudo_pair_unpack_directory }}/target/release/libsudo_pair.so"
   environment:
     PATH:$PATH:/usr/local/bin

- name: install software
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    remote_src: yes
  with_items:
    - "{{ sudo_pair_files }}"

- name: create directories
  file:
    path: "{{ sudo_pair_directories }}"
    state: directory
    owner: root
    group: root
    mode: 0644

- name: configure sudo
  template:
    src: sudo.conf.j2
    dest: /etc/sudo.conf
    owner: root
    group: root
    mode: "0644"
