---
# vars file for sudo-pair
sudo_pair_url: "https://github.com/square/sudo_pair/archive/{{ sudo_pair_version }}.zip"
sudo_pair_unpack_directory: /tmp/sudo-pair

sudo_pair_lib_directory: /usr/libexec/sudo

sudo_pair_files:
  - src: "{{ sudo_pair_unpack_directory }}/sample/bin/sudo_approve"
    dest: /usr/bin/sudo_approve
    mode: "0755"
  - src: "{{ sudo_pair_unpack_directory }}/sample/etc/sudo.prompt.user"
    dest: /etc/sudo.prompt.user
    mode: "0644"
  - src: "{{ sudo_pair_unpack_directory }}/sample/etc/sudo.prompt.pair"
    dest: /etc/sudo.prompt.pair
    mode: "0644"
  - src: "{{ sudo_pair_unpack_directory }}/target/release/libsudo_pair.so"
    dest: "{{ sudo_pair_lib_directory }}"
    mode: "0644"

sudo_pair_directories:
  - /var/run/sudo_pair

sudo-pair_binary_path: /usr/bin/sudo_approve
sudo-pair_user_prompt_path: /etc/sudo_pair.prompt.user
sudo-pair_pair_prompt_path: /etc/sudo_pair.prompt.pair
sudo-pair_socket_dir: /var/run/sudo_pair

sudo_pair_requirements:
  - cargo
  - git
